{% set version = "0.18.7" %}

package:
  name: ruamel.yaml
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/ruamel.yaml/ruamel.yaml-{{ version }}.tar.gz
  sha256: 270638acec6659f7bb30f4ea40083c9a0d0d5afdcef5e63d666f11209091531a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  script_env:
    - RUAMEL_NO_LONG_DESCRIPTION=1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - ruamel
    - setuptools
  run:
    - python
    - ruamel.yaml.clib >=0.1.2

test:
  imports:
    - ruamel.yaml

about:
  home: https://sourceforge.net/p/ruamel-yaml
  license: MIT
  license_file: LICENSE
  summary: A YAML package for Python. It is a derivative of Kirill Simonov's PyYAML 3.11 which supports YAML1.1

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - mwcraig
    - ocefpaf
    - mbargull
    - xhochy
    - davidbrochart
