{% set version = "0.18.1" %}

package:
  name: ruamel.yaml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/ruamel.yaml/ruamel.yaml-{{ version }}.tar.gz
  sha256: 649a301890441d36ea9cb0f48d07353de82b8cbde2244387e7ef6b1d3b9ee6cd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  script_env:
    - RUAMEL_NO_LONG_DESCRIPTION=1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - ruamel
  run:
    - python
    - setuptools
    - ruamel.yaml.clib >=0.1.2

test:
  imports:
    - ruamel.yaml

about:
  home: https://sourceforge.net/p/ruamel-yaml
  license: MIT
  license_file: LICENSE
  summary: A YAML package for Python. It is a derivative of Kirill Simonov's PyYAML 3.11 which supports YAML1.1

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - mwcraig
    - ocefpaf
    - mbargull
    - xhochy
    - davidbrochart
