{% set version = "0.16.7" %}

package:
  name: ruamel.yaml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/ruamel.yaml/ruamel.yaml-{{ version }}.tar.gz
  sha256: 9d59fa89985c55155d35c886663e357813404ae8f94638cb673135b8c8c1a7c7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - ruamel
  run:
    - python
    - setuptools
    - ruamel.yaml.clib >=0.1.2
    - ruamel.ordereddict  # [py27]

test:
  imports:
    - ruamel.yaml

about:
  home: https://bitbucket.org/ruamel/yaml
  license: MIT
  license_file: LICENSE
  summary: "A YAML package for Python. It is a derivative of Kirill Simonov's PyYAML 3.11 which supports YAML1.1"

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - mwcraig
    - ocefpaf
    - mbargull
