# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.19.1"
  python_check_max: "3.14"

package:
  name: ruamel.yaml
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/ruamel.yaml/ruamel_yaml-${{ version }}.tar.gz
  sha256: 53eb66cd27849eff968ebf8f0bf61f46cdac2da1d1f3576dd4ccee9b25c31993

build:
  number: 0
  noarch: python
  script:
    env:
      RUAMEL_NO_LONG_DESCRIPTION: "1"
    content:
      - ${{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - ruamel
    - setuptools
  run:
    - python >=${{ python_min }}
    # [oldlibyaml]
    - ruamel.yaml.clib >=0.2.15
    # [libyaml]
    # - ruamel.yaml.clibz>=0.3.7


tests:
  - python:
      imports:
        - ruamel.yaml
        - ruamel.yaml.cyaml
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*

about:
  license: MIT
  license_file: LICENSE
  summary: A YAML package for Python. It is a derivative of Kirill Simonov's PyYAML 3.11 which supports YAML1.1
  homepage: https://pypi.org/project/ruamel.yaml
  repository: https://sourceforge.net/p/ruamel-yaml
  documentation: https://yaml.dev/doc/ruamel.yaml

extra:
  recipe-maintainers:
    - bollwyvl
    - davidbrochart
    - jakirkham
    - mbargull
    - mwcraig
    - ocefpaf
    - pelson
    - xhochy
