# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.19.0"
  ruamel_yaml_clib_min: "0.2.15"

package:
  name: ruamel.yaml
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/ruamel.yaml/ruamel_yaml-${{ version }}.tar.gz
  sha256: ff19233e1eb3e9301e7a3d437847713e361a80faace167639327efbe8c0e5f95

build:
  number: 0
  script:
    env:
      RUAMEL_NO_LONG_DESCRIPTION: "1"
    content:
      - ${{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
  host:
    - pip
    - python
    - ruamel
    - setuptools
  run:
    - python
    - ruamel.yaml.clib >=${{ ruamel_yaml_clib_min }}

tests:
  - python:
      imports: ruamel.yaml
      pip_check: true
  - requirements:
      run:
        - pip
        - ruamel.yaml.clib ${{ ruamel_yaml_clib_min }}.*
    script:
      - pip check

about:
  license: MIT
  license_file: LICENSE
  summary: A YAML package for Python. It is a derivative of Kirill Simonov's PyYAML 3.11 which supports YAML1.1
  homepage: https://pypi.org/project/ruamel.yaml
  repository: https://sourceforge.net/p/ruamel-yaml
  documentation: https://yaml.dev/doc/ruamel.yaml

extra:
  recipe-maintainers:
    - bollwyvl
    - davidbrochart
    - jakirkham
    - mbargull
    - mwcraig
    - ocefpaf
    - pelson
    - xhochy
