appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: vWwaKVJyL4RWgmorM/6nDWLj7QrChLD708onzfs357MeDcRvU78oiWMC/60oSpnqAVMsh5uqUQIlrEXmuqh88aJoK3fziHoTI2RC5ZFPrdYnal0luzvpJnzI8AWKjgkuRIxb3qD2OtTftj8jDiALn4+WJ5MhK7LcRfaid9NqZaXJKgdfuzJO3yxYIQ45wPJbtVDvrnjgL6dO47zNuahpXfPzZ2e6k9sTuhwEyDJ3qASTSSxW+ygw791OIi1HVfWl6c7OrR6GevuKiYMBshTC/jr2qPkT3520iddhddC6oh8f82+iOGtAeNXtOCSUUsUBCarROUmMD0l4bqZR7hUj/3gpwEfguUq/EPCVU0b276L6Za2IzAXuZVabN43tyZUlMMqHeSN7mYhqnwfv0nt5QETpIpM0MmaiYl2rMooolXaUgnESGILxnZjn0UWaWpREiIl3Wpg0BKpnDiDFTgAOrddTtY0yKvkfoyUb7bq/AbEuAIwlUcp1mlE+tYlVvWc3gUJaAJYGyKZUa+P0IBV6np5gBhtqxWJ6ZziiSYj4dTLivW0Zisz+bei+fgWibELHUhgpJZ0xm4uz37uB0zO1xWV1A7fs+fd7f/Fqe3uo88oxLhVEpBaNCSD4zUooTYlvjEVO+eIYPwESmQKpfuQLMGzo0NwA13TuEUpx1H3y8XU=}
conda_forge_output_validation: false
